$(document).ready(function(){
	$('.company__img_cons').hover(function(){
		$('.company__block').hide();
	    $('.company__cons').show();
	});
	$('.company__img_photo').hover(function(){
		$('.company__block').hide();
	    $('.company__photo').show();
	});
	$('.company__img_web').hover(function(){
		$('.company__block').hide();
	    $('.company__web').show();
	});
	$('.company__img_advert').hover(function(){
		$('.company__block').hide();
	    $('.company__advert').show();
	});

});